export const LOCALIZATION = {
  down: 'Down',
  hiScorePrefix: 'Hi-',
  left: 'Left',
  level: 'Level',
  racing: 'Racing',
  right: 'Right',
  rotate: 'Rotate',
  score: 'Score',
  snake: 'Snake',
  speed: 'Speed',
  tanks: 'Tanks',
  tetris: 'Tetris',
  up: 'Up',
}
